from enum import Enum

__NAMESPACE__ = "http://www.netex.org.uk/netex"


class SimpleVehicleCategoryEnumeration(Enum):
    SCOOTER = "scooter"
    E_SCOOTER = "eScooter"
    CYCLE = "cycle"
    PEDAL_CYCLE = "pedalCycle"
    E_CYCLE = "eCycle"
    TRICYCLE = "tricycle"
    TANDEM = "tandem"
    MOPED = "moped"
    MOTORCYCLE = "motorcycle"
    QUADBIKE = "quadbike"
    CAR = "car"
    MICRO_CAR = "microCar"
    MINI_CAR = "miniCar"
    SMALL_CAR = "smallCar"
    MEDIUM_CAR = "mediumCar"
    LARGE_CAR = "largeCar"
    MINIVAN = "minivan"
    TRANSPORTER = "transporter"
    VAN = "van"
    SNOWMOBILE = "snowmobile"
    MOTORCYCLE_WITH_SIDECAR = "motorcycleWithSidecar"
    MOTOR_SCOOTER = "motorScooter"
    TWO_WHEELED_VEHICLE = "twoWheeledVehicle"
    THREE_WHEELED_VEHICLE = "threeWheeledVehicle"
    PASSENGER_CAR = "passengerCar"
    FOUR_WHEEL_DRIVE = "fourWheelDrive"
    TAXI = "taxi"
    CAMPER_CAR = "camperCar"
    CARAVAN = "caravan"
    CAR_WITH_TRAILER = "carWithTrailer"
    CAR_WITH_CARAVAN = "carWithCaravan"
    MINIBUS = "minibus"
    UNDEFINED = "undefined"
    OTHER = "other"
    ALL_PASSENGER_VEHICLES = "allPassengerVehicles"
    ALL = "all"
