from enum import Enum

__NAMESPACE__ = "http://www.netex.org.uk/netex"


class StakeholderRoleTypeEnumeration(Enum):
    PLANNING = "planning"
    OPERATION = "operation"
    CONTROL = "control"
    RESERVATION = "reservation"
    ENTITY_LEGAL_OWNERSHIP = "entityLegalOwnership"
    FARE_MANAGEMENT = "fareManagement"
    FINANCING = "financing"
    SECURITY_MANAGEMENT = "securityManagement"
    CUSTOMER_SERVICE = "customerService"
    DATA_REGISTRAR = "dataRegistrar"
    TENANT = "tenant"
    FACILITY_MANAGEMENT = "facilityManagement"
    LESSOR = "lessor"
    OTHER = "other"
    PLANNING_1 = "Planning"
    OPERATION_1 = "Operation"
    CONTROL_1 = "Control"
    RESERVATION_1 = "Reservation"
    ENTITY_LEGAL_OWNERSHIP_1 = "EntityLegalOwnership"
    FARE_MANAGEMENT_1 = "FareManagement"
    FINANCING_1 = "Financing"
    SECURITY_MANAGEMENT_1 = "SecurityManagement"
    CUSTOMER_SERVICE_1 = "CustomerService"
    DATA_REGISTRAR_1 = "DataRegistrar"
    TENANT_1 = "Tenant"
    FACILITY_MANAGEMENT_1 = "FacilityManagement"
    LESSOR_1 = "Lessor"
    OTHER_1 = "Other"
