from enum import Enum

__NAMESPACE__ = "http://www.siri.org.uk/siri"


class CoachSubmodesOfTransportEnumeration(Enum):
    UNKNOWN = "unknown"
    UNDEFINED = "undefined"
    INTERNATIONAL_COACH = "internationalCoach"
    NATIONAL_COACH = "nationalCoach"
    SHUTTLE_COACH = "shuttleCoach"
    REGIONAL_COACH = "regionalCoach"
    SPECIAL_COACH = "specialCoach"
    SCHOOL_COACH = "schoolCoach"
    SIGHTSEEING_COACH = "sightseeingCoach"
    TOURIST_COACH = "touristCoach"
    COMMUTER_COACH = "commuterCoach"
    INTERNATIONAL_COACH_SERVICE = "internationalCoachService"
    NATIONAL_COACH_SERVICE = "nationalCoachService"
    SHUTTLE_COACH_SERVICE = "shuttleCoachService"
    REGIONAL_COACH_SERVICE = "regionalCoachService"
    ADDITIONAL_COACH_SERVICE = "additionalCoachService"
    NIGHT_COACH_SERVICE = "nightCoachService"
    SPECIAL_COACH_SERVICE = "specialCoachService"
    SIGHTSEEING_COACH_SERVICE = "sightseeingCoachService"
    TOURIST_COACH_SERVICE = "touristCoachService"
    COMMUTER_COACH_SERVICE = "commuterCoachService"
    ON_DEMAND_SERVICE = "onDemandService"
    UNDEFINED_COACH_SERVICE = "undefinedCoachService"
    ALL_COACH_SERVICES = "allCoachServices"
    PTI3_0 = "pti3_0"
    PTI3_1 = "pti3_1"
    PTI3_2 = "pti3_2"
    PTI3_3 = "pti3_3"
    PTI3_4 = "pti3_4"
    PTI3_5 = "pti3_5"
    PTI3_6 = "pti3_6"
    PTI3_7 = "pti3_7"
    PTI3_8 = "pti3_8"
    PTI3_9 = "pti3_9"
    PTI3_255 = "pti3_255"
