from enum import Enum

__NAMESPACE__ = "http://www.siri.org.uk/siri"


class RoutePointTypeEnumeration(Enum):
    UNKNOWN = "unknown"
    ORIGIN = "origin"
    DESTINATION = "destination"
    INTERMEDIATE = "intermediate"
    LEG_BOARD = "legBoard"
    LEG_INTERMEDIATE = "legIntermediate"
    LEG_ALIGHT = "legAlight"
    FIRST_ROUTE_POINT = "firstRoutePoint"
    LAST_ROUTE_POINT = "lastRoutePoint"
    AFFECTED_STOPPLACE = "affectedStopplace"
    PRESENTED_STOPPLACE = "presentedStopplace"
    UNDEFINED_STOPPLACE_USAGE = "undefinedStopplaceUsage"
    START_POINT = "startPoint"
    STOP = "stop"
    VIA = "via"
    NOT_STOPPING = "notStopping"
    TEMPORARY_STOP = "temporaryStop"
    TEMPORARILY_NOT_STOPPING = "temporarilyNotStopping"
    EXCEPTIONAL_STOP = "exceptionalStop"
    ADDITIONAL_STOP = "additionalStop"
    REQUEST_STOP = "requestStop"
    FRONT_TRAIN_DESTINATION = "frontTrainDestination"
    REAR_TRAIN_DESTINATION = "rearTrainDestination"
    THROUGH_SERVICE_DESTINATION = "throughServiceDestination"
    NOT_VIA = "notVia"
    ALTERED_START_POINT = "alteredStartPoint"
    ALTERED_DESTINATION = "alteredDestination"
    UNDEFINED_ROUTE_POINT = "undefinedRoutePoint"
