from enum import Enum

__NAMESPACE__ = "http://www.siri.org.uk/siri"


class TelecabinSubmodesOfTransportEnumeration(Enum):
    UNKNOWN = "unknown"
    UNDEFINED = "undefined"
    TELECABIN = "telecabin"
    CABLE_CAR = "cableCar"
    LIFT = "lift"
    CHAIR_LIFT = "chairLift"
    DRAG_LIFT = "dragLift"
    TELECABIN_LINK = "telecabinLink"
    SCHEDULED = "scheduled"
    UNSCHEDULED = "unscheduled"
    UNDEFINED_TELECABIN_SERVICE = "undefinedTelecabinService"
    SMALL_TELECABIN = "smallTelecabin"
    EGG_LIFT = "eggLift"
    MINERAL_BUCKETS = "mineralBuckets"
    ALL_TELECABIN_SERVICES = "allTelecabinServices"
    PTI9_0 = "pti9_0"
    PTI9_1 = "pti9_1"
    PTI9_2 = "pti9_2"
    PTI9_3 = "pti9_3"
    PTI9_4 = "pti9_4"
    PTI9_5 = "pti9_5"
    PTI9_6 = "pti9_6"
    PTI9_7 = "pti9_7"
    PTI9_255 = "pti9_255"
    LOC14_0 = "loc14_0"
    LOC14_1 = "loc14_1"
    LOC14_3 = "loc14_3"
    LOC14_4 = "loc14_4"
    LOC14_52 = "loc14_52"
    LOC14_6 = "loc14_6"
    LOC14_7 = "loc14_7"
    LOC14_8 = "loc14_8"
    LOC14_255 = "loc14_255"
