from enum import Enum

__NAMESPACE__ = "http://www.siri.org.uk/siri"


class TramSubmodesOfTransportEnumeration(Enum):
    UNKNOWN = "unknown"
    UNDEFINED = "undefined"
    CITY_TRAM = "cityTram"
    LOCAL_TRAM = "localTram"
    REGIONAL_TRAM = "regionalTram"
    SIGHTSEEING_TRAM = "sightseeingTram"
    SHUTTLE_TRAM = "shuttleTram"
    TRAIN_TRAM = "trainTram"
    TRAM_SERVICE = "tramService"
    CITY_TRAM_SERVICE = "cityTramService"
    REGIONAL_TRAM_SERVICE = "regionalTramService"
    SIGHTSEEING_TRAM_SERVICE = "sightseeingTramService"
    NIGHT_TRAM_SERVICE = "nightTramService"
    SHUTTLE_TRAM_SERVICE = "shuttleTramService"
    UNDEFINED_URBAN_RAILWAY_SERVICE = "undefinedUrbanRailwayService"
    LOCAL_TRAM_SERVICE = "localTramService"
    UNDEFINED_TRAM_SERVICE = "undefinedTramService"
    ALL_TRAM_SERVICES = "allTramServices"
    PTI6_0 = "pti6_0"
    PTI6_1 = "pti6_1"
    PTI6_2 = "pti6_2"
    PTI6_3 = "pti6_3"
    PTI6_4 = "pti6_4"
    PTI6_5 = "pti6_5"
    PTI6_6 = "pti6_6"
    PTI6_255 = "pti6_255"
    LOC12_0 = "loc12_0"
    LOC12_1 = "loc12_1"
    LOC12_2 = "loc12_2"
    LOC12_255 = "loc12_255"
